apiVersion: v1
kind: Service
metadata:
  name: aws-queue-reponook-svc
  labels:
    app: aws-queue-reponook-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8191
      targetPort: aws-queue-repo-port
      protocol: TCP
      name: http
  selector:
    app: aws-queue-reponook
